name: GH Page Post-merge

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        working-directory: documentation
        run: |
          npm install
          npm run build
      - name: Deploy
        working-directory: documentation
        env:
          TRBOX_RSA_PRIV: ${{ secrets.TRBOX_ID_RSA }}
          TRBOX_HOSTNAME: ${{ secrets.TRBOX_HOSTNAME }}
        run: |
          echo "${TRBOX_RSA_PRIV}" > /tmp/id_rsa
          scp -i /tmp/id_rsa dist/documentation/* ${TRBOX_HOSTNAME}:~/plank_bin/public/
