name: GH Page Post-merge

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        working-directory: documentation
        run: |
          npm install
          npm run build
          cp dist/documentation/index.html dist/documentation/404.html  
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          token: ${{ secrets.GH_PAGE_DEPLOY_PAT }}
          folder: documentation/dist/documentation


